# this is simply copied over from config/config_designers.yml

# project definitions
project: mydoc_designers
audience: developers
product: doc
platform: all
version: all
output: web
# destination: ../doc_outputs/mydoc/designers
url: "scalainc.github.io/exp-docs"
title: EXP Docs
topnav_title: EXP Docs
homepage_title: EXP Docs
site_title: Documentation for EXP Platform
project_folder: mydoc
company_name: EXP
footer_image_location: /common_images/exp_logo_large.svg
github_editme_path: scalainc/exp-docs/edit/gh-pages
relative_permalinks: false

# variables

sidebar_tagline: Developers
sidebar_version: Version 1.0
theme_file: theme-blue.css
pdf_file_name: mydoc_designers_pdf.pdf

# the algolia entries here are experimental only.

#gems:
#  - algoliasearch-jekyll
#algolia:
#  application_id: 'HXUBJERYYB'
#  index_name:     'documentation_theme_jekyll_designers'
port: 4009
include:
  - _pages
exclude:
  - _site
  - _drafts
  - configs/
  - doc/mydoc_writers*

# same for all
host: 127.0.0.1
feedback_email: replace-me@scala.com

highlighter: rouge
markdown: kramdown
kramdown:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]


collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

